trigger:
- main

pool:
  vmImage: 'macos-latest'

variables:
  ANDROID_HOME: /Users/runner/Library/Android/sdk
  EMULATOR_NAME: xamarin_android_emulator

steps:
- task: CmdLine@2
  displayName: 'Install Latest .NET MAUI Workload'
  inputs:
    script: 'dotnet workload install maui'
    
- script: |
    echo "##[group]Dotnet Tool Restore"
    cd /Users/runner/work/1/s/maui
    dotnet tool restore
    echo "##[endgroup]"
  displayName: 'Dotnet Tool Restore'

- script: |
    echo "##[group]Build the build tasks"
    cd /Users/runner/work/1/s/maui
    dotnet build ./Microsoft.Maui.BuildTasks.slnf
    echo "##[endgroup]"
  displayName: 'Build Tasks'
