trigger:
- main

pool:
  vmImage: 'macos-latest'

variables:
  ANDROID_HOME: /Users/runner/Library/Android/sdk
  EMULATOR_NAME: xamarin_android_emulator

steps:
- task: CmdLine@2
  displayName: 'Install Latest .NET MAUI Workload'
  inputs:
    script: 'dotnet workload install maui'

- task: CmdLine@2
  displayName: 'Check Workload List'
  inputs:
    script: 'dotnet workload list'

- task: CmdLine@2
  displayName: 'Install Latest .NET MAUI Tizen Workload'
  inputs:
    script: 'dotnet workload install tizen'


- script: |
    echo "##[group]Dotnet Tool Restore"
    cd /Users/runner/work/1/s/maui
    dotnet tool restore
    echo "##[endgroup]"
  displayName: 'Dotnet Tool Restore'

- script: |
    echo "##[group]Dotnet Workload Restore"
    cd /Users/runner/work/1/s/maui
    dotnet cake --target=dotnet-local-workloads
    echo "##[endgroup]"
  displayName: 'Dotnet Workload Restore'
  continueOnError: true

- script: |
    echo "##[group]Build the build tasks"
    cd /Users/runner/work/1/s/maui
    dotnet build ./Microsoft.Maui.BuildTasks.slnf
    echo "##[endgroup]"
  displayName: 'Build Tasks'
